export const NOTIFICATION_LIST = [
  'PENDING_FRIEND_REQUEST',
  'ACCEPTED_FRIEND_REQUEST',
  'MESSAGE',
  'POST',
  'STATUS_UPDATE'
] as const;

export const NOTIFICATION_STATUS_LIST = [
  'UNREAD',
  'READ',
] as const;
